config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :cart_details
  resources :carts
  resources :purchases
  get "/cart/add_to_cart", to: "carts#add_to_cart"
  post "/create_user", to: "admin#create_user"
  devise_for :users
  devise_for :views
  root to: "home#index"

  get 'home/index'
  resources :reviews
  resources :users, shallow: true
  resources :books, shallow: true
  resources :admin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :purchases, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true, email: {mode: :rfc}

  validates :username, presence: true, uniqueness: true
  validates :name, presence: true

  # Custom validations
  validate :credit_card_validation
  validate :phone_number_validation

  def numeric_string_check(string)
    string.scan(/^\d+$/).present?
  end

  def credit_card_validation
    unless self.credit_card.nil? or self.credit_card.empty?
      unless self.credit_card.length == 16
        errors.add(:credit_card, 'must be 16 digits long')
      end
      unless numeric_string_check(self.credit_card)
        errors.add(:credit_card, 'must contain only numbers')
      end
    end
  end

  def phone_number_validation
    unless self.phone_number.nil? or self.phone_number.empty?
      unless self.phone_number.length == 10
        errors.add(:phone_number, 'must be 10 digits long')
      end

      unless numeric_string_check(self.phone_number)
        errors.add(:phone_number, 'must contain only numbers')
      end
    end
  end




  # validates :credit_card, length: { is: 16 }
  # validates :phone_number, length: { is: 10 }
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_valid_user!, only: %i[ show edit update destroy ]


  def authenticate_valid_user!
    if current_user.present? and current_user.id != @user.id
      redirect_to root_path, alert: "Sorry, you are not allowed to access/modify that page!"
    end
  end

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    user_params_empty_pass = user_params.reject {|k, v| v == "" and k == 'password'}
    respond_to do |format|
      if @user.update(user_params_empty_pass)
        sign_in(@user, :bypass => true)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    if current_user.present? and current_user.id == @user.id
      @user.destroy
      redirect_to destroy_user_session_path
    else
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
        # format.html { redirect_to root_path, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :name, :email, :address, :credit_card, :phone_number)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :credit_card %>
    <%= form.text_field :credit_card %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user, url: create_user_path(user), html: { method: :post }) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  
  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :credit_card %>
    <%= form.text_field :credit_card %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>
<br>
<% if current_admin.present? %>
  <%= link_to 'View all users', users_path %>
  <br>
<% end %>
<%= link_to 'Home', root_path %>

app/views/users/index.html.erb
<% if current_admin.present? %>
  <h1>Users</h1>

  <table>
    <thead>
      <tr>
        <th>Username</th>
        <th>Name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.username , user %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= button_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

<%= link_to 'New User', new_user_path %>
<% else %>
 <!-- TODO: Have the check in the controller too (send 403) -->
 <p>You cannot view this page! (Not an admin)</p>
<% end %>

<br>
<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'View all users', users_path %>
<br>
<%= link_to 'Home', root_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Credit card number:</strong>
  <%= @user.credit_card %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @user.phone_number %>
</p>

<%= link_to 'Back', users_path %>
<br>
<%= link_to 'Home', root_path %>