config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :cart_details
  resources :carts
  resources :purchases
  get "/cart/add_to_cart", to: "carts#add_to_cart"
  post "/create_user", to: "admin#create_user"
  devise_for :users
  devise_for :views
  root to: "home#index"

  get 'home/index'
  resources :reviews
  resources :users, shallow: true
  resources :books, shallow: true
  resources :admin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :create_cart
  
  def index
  end

  private
    def create_cart
      if(!current_user.nil?)
        carts = Cart.where(user_id: current_user.id)
        purchases = Purchase.where(cart_id: carts)
        if(carts.empty? == true || carts.size == purchases.size)
          Cart.create(user_id: current_user.id)
        end
      end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Nozama Book Shop</h1>
<% if current_admin.present? %>
Welcome, <%= current_admin.name.capitalize %><br>
<br>
<%= link_to 'View Books', books_path %><br>
<%= link_to 'View Reviews', reviews_path %><br>
<%= link_to 'View all users', users_path %><br>
<%= link_to 'View Profile', admin_path(current_admin) %><br>
<%= link_to 'Edit Profile', edit_admin_url(current_admin) %><br>
<%= link_to 'Logout', destroy_admin_session_path %><br>


<% elsif current_user.present? %>
Welcome <%= current_user.name.capitalize %><br>
<br>
<%= link_to 'View Books', books_path %><br>
<%= link_to 'View Reviews', reviews_path %><br>
<%= link_to 'View Cart', cart_details_path %><br>
<%= link_to 'View Previous Transactions', purchases_path %><br>
<%= link_to 'Edit Profile', edit_user_url(current_user) %><br>
<%= link_to 'Logout', destroy_user_session_path %>
<%= button_to 'Delete Profile', user_path(current_user), method: :delete, data: { confirm: 'Are you sure?' } %>


<% else %>
Welcome, guest<br>
<%= link_to 'User Login', new_user_session_path %><br>
<%= link_to 'User SignUp', new_user_registration_path %><br>
<%= link_to 'Admin Login', new_admin_session_path %><br>
<% end %>