config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :cart_details
  resources :carts
  resources :purchases
  get "/cart/add_to_cart", to: "carts#add_to_cart"
  post "/create_user", to: "admin#create_user"
  devise_for :users
  devise_for :views
  root to: "home#index"

  get 'home/index'
  resources :reviews
  resources :users, shallow: true
  resources :books, shallow: true
  resources :admin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :reviews, dependent: :destroy
    has_many :cart_details, dependent: :destroy

    validate :price_numeric_check

    def price_numeric_check
        if self.price.nil? or self.price <= 0
            errors.add(:price, 'must be a positive number')
        end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @filtered = false
    if(params[:author].nil? or params[:author].empty?)
      @books = Book.all
    else
      @filtered = true
      @books = Book.where(author: params[:author])
    end

    @ratings = []
    if(params[:rating].present?)
      @filtered = true
      booksAboveRating = []
      @books.each do |b|
        reviews = Review.where(book_id: b.id)
        if(reviews.present?)
          rating = (reviews.map(&:rating).inject(:+).to_f)/reviews.size
          if(rating > params[:rating].to_f)
            booksAboveRating.push(b)
            @ratings.push(rating)
          end
        end
      end
      @books = booksAboveRating
    else
      @books.each do |b|
        reviews = Review.where(book_id: b.id)
        if(reviews.empty?)
          @ratings.push(0)
        else 
          @ratings.push((reviews.map(&:rating).inject(:+).to_f)/reviews.size)
        end
      end
    end
  end

  # GET /books/1 or /books/1.json
  def show
    if current_admin.present?
      @is_a_admin = true
    elsif current_user.present?
      @is_a_admin = false
      cart = Cart.where(user_id: current_user.id).order("created_at").last
      cart_detail = CartDetail.where(cart_id: cart.id, book_id: @book.id)
      if cart_detail.empty?
        @alreadyPresent = false 
      else
        @alreadyPresent = true 
      end
    end
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :author, :publisher, :price, :stock)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :publisher %>
    <%= form.text_field :publisher %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %><br>
<%= link_to 'Home', root_path %>

app/views/books/index.html.erb
<%= form_tag("/books", method: "get") do %>
  <%= label_tag(:author, "Author") %>
  <%= text_field_tag(:author) %>
  <%= submit_tag("Filter By Author") %>
<% end %>

<%= form_tag("/books", method: "get") do %>
  <%= label_tag(:rating, "Rating") %>
  <%= number_field_tag(:rating, nil, min: 1, max: 5, step: 0.1) %>
  <%= submit_tag("Filter by Rating") %>
<% end %>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Price</th>
      <th>Stock</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% i = 0 %>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= book.price %></td>
        <td><%= book.stock %></td>
        <td><%= @ratings[i] %></td>
        <% i = i + 1 %>
        <% if book.stock != 0 && current_user.present? %>
          <td><%= link_to 'Buy/Show', book_path(book) %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to 'Write a review', new_review_path(:book_id => book.id) %></td>
        <% if current_admin.present? %>
          <td><%= link_to 'Show', book %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= button_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_admin.present? %>
  <td><%= link_to 'New Book', new_book_path %></td>
<% end %>
<br>
<% if @filtered %>
<%= link_to 'View all books', books_path %>
<br>
<% end %>

<%= link_to 'View All Reviews', reviews_path %>
<br>
<% unless current_admin.present? %>
  <%= link_to 'View Cart', cart_details_path %><br>
<% end %>
<% if(current_user.present? or current_admin.present?) %>
      <%= link_to 'Home', root_path %>
<% end %>
<br>
<%= link_to 'Logout', destroy_user_session_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<% if current_user.present? %>
<p>
  <strong>Quantity:</strong>
  <% quantity = [] %>
  <% (1..@book.stock).each do |i| quantity << [i.to_s, i] %>
  <% end %>
  <%= form_with url: "/cart/add_to_cart", method: :get do |form| %>
    <%= form.hidden_field :book_id, value: @book.id %>
    <%= select_tag(:quantity, options_for_select(quantity)) %>

  <% unless @is_a_admin %>
    <% if @alreadyPresent %>
    <%= form.submit "Update cart" %>
    <% else %> 
    <%= form.submit "Add to cart" %>
    <% end %>
  <% end %>

  <% end %>
</p>
<% end %>


<%= link_to 'Review this book', new_review_path(@book) %>
<br>
<%= link_to 'Back', books_path %>
<br>
<%= link_to 'Home', root_path %>