config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :cart_details
  resources :carts
  resources :purchases
  get "/cart/add_to_cart", to: "carts#add_to_cart"
  post "/create_user", to: "admin#create_user"
  devise_for :users
  devise_for :views
  root to: "home#index"

  get 'home/index'
  resources :reviews
  resources :users, shallow: true
  resources :books, shallow: true
  resources :admin
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]
  before_action :authenticate_valid_user!, only: %i[edit update destroy]


  def authenticate_valid_user!
    @review_user_id = @review.user_id

    # If it is an admin, the if condition would fail and we will be able to access
    # If it is an user and the review user is different, then we redirect with notice
    if current_user.present? and current_user.id != @review_user_id
      redirect_to root_path, alert: "Sorry, you are not allowed to access/modify that page!"
    end
  end

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
    @selectedUser = ""
    @selectedBook = ""
    if(params[:user].present?)
      @reviews = Review.where(user_id: params[:user])
      @selectedUser = params[:user]
    elsif(params[:book].present?)
      @reviews = Review.where(book_id: params[:book])
      @selectedBook = params[:book]
    end
    @book_names = []
    @user_names = []
    @reviews.each do |r|
      @book_names.push(Book.find_by(id: r.book_id).name)
      @user_names.push(User.find_by(id: r.user_id).username)
    end
    @people = User.all
    @book = Book.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
    if(@review.user_id)
      @user = User.find_by(id: @review.user_id)
    else
      @admin = Admin.find_by(id: @review.admin_id)
    end
    @book = Book.find_by(id: @review.book_id)
  end

  # GET /reviews/new
  def new
    @review = Review.new
    @book = params[:book_id]
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    rating = review_params['rating']
    review = review_params['review']
    review_params = {"book_id": @review.book_id, "user_id": @review.user_id, "rating": rating, "review": review}
    puts review_params

    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def review_by_admin?
      params[:review][:admin_id] ? true : false
    end

    def admin_id_for_review
      params[:review][:admin_id]
    end

    # Only allow a list of trusted parameters through
    def review_params
      params.require(:review).permit(:rating, :review, :user_id, :book_id, :admin_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if review.persisted? %>
    <% if review.admin_id %>
      <div class="field">
      <%= form.hidden_field :admin_id, value: review.admin_id %>
      </div>
    <% else %>
      <div class="field">
      <%= form.hidden_field :user_id, value: review.user_id %>
      </div>
    <% end %>
  <% else %>
    <% if current_user.present? %>
      <div class="field">
        <%= form.hidden_field :user_id, value: current_user.id %>
      </div>
    <% elsif current_admin.present? %>
      <div class="field">
        <%= form.hidden_field :admin_id, value: current_admin.id %>
      </div>
    <% end %>
  <% end %>

  <div class="field">
    <%= form.hidden_field :book_id, value: @book %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating, max: 5, min: 1 %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %> <br>
<%= link_to 'Home', root_path %>

app/views/reviews/index.html.erb
<%= form_tag("/reviews", method: "get") do %>
  <%= label_tag(:user, "User") %>
  <%= select_tag(:user, options_from_collection_for_select(@people, "id", "username", @selectedUser),  :include_blank => true) %>
  <%= submit_tag("Filter By User") %>
<% end %>

<%= form_tag("/reviews", method: "get") do %>
  <%= label_tag(:book, "Book") %>
  <%= select_tag(:book, options_from_collection_for_select(@book, "id", "name", @selectedBook),  :include_blank => true) %>
  <%= submit_tag("Filter By Book") %>
<% end %>

<%= link_to 'Display all reviews', reviews_path %>

<h1>Reviews</h1>
<table>
  <thead>
    <tr>
      <th>Book Name</th>
      <th>Username</th>
      <th>Rating</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% i = 0 %>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= @book_names[i] %></td>
        <td><%= @user_names[i] %></td>
        <% i = i + 1 %>
        <td><%= review.rating %></td>
        <td><%= review.review %></td>
        <td><%= link_to 'Show', review %></td>
        <% if (current_admin.present? or review.user_id == current_user.id) %>
          <td><%= link_to 'Edit', edit_review_path(review) %></td>
          <td><%= button_to 'Delete', review_path(review), method: :delete%></td>
        <% else %>
          <td> </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'View Books', books_path %>
<br>
<% unless current_admin.present? %>
  <%= link_to 'View Cart', cart_details_path %>
  <br>
<% end %>
<%= link_to 'Home', root_path %>
<br>
<%= link_to 'Logout', destroy_user_session_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<br>
<%= link_to 'Back', books_path %>
<br>
<%= link_to 'Home', root_path %>

app/views/reviews/show.html.erb
<p>
  <% if @user %>
    <strong>User:</strong>
    <%= @user.email %>
  <% else %>
    <strong>Admin:</strong>
    <%= @admin.email %>
  <% end %>
</p>

<p>
  <strong>Book Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Review:</strong>
  <%= @review.review %>
</p>

<%= link_to 'Back', reviews_path %> <br>
<%= link_to 'Home', root_path %>